docker-build:
	docker-compose build

docker-up:
	docker-compose up -d

docker-reload:
	docker-compose up -d --build microservice
	docker-compose up -d --build microservice2

docker-down:
	docker-compose down
